import type { Locale } from "../locale";

interface AboutDict {
  heading: string;
  intro: string;
  hypothesisHeading: string;
  hypothesisBody: string;
  aiHeading: string;
  aiBody: string;
  differentiationHeading: string;
  differentiationBody: string;
}

export const aboutDict: Record<Locale, AboutDict> = {
  ja: {
    heading: "このサイトについて",
    intro:
      "「Notewave」は、曲やあなたの演奏・歌声を対象に、音響物理・幾何学(Tonnetz)・フーリエ解析・情報理論(シャノンエントロピー)に基づく数理的な解析を行うインタラクティブツールです。",
    hypothesisHeading: "数値が意味すること",
    hypothesisBody:
      "「美しさと相関しうる数理的特徴」(協和度・和声的テンション・予測可能性・自己相似性)や、感情推定(valence/arousal)は、いずれも音楽理論・情報理論上の数学的な指標と、曲の印象やキャッチーさとの相関に基づく仮説的な視点です。曲がなぜ美しく聴こえるか、なぜ耳に残るかを証明するものではありません。感情推定についても、検証済みの感情認識モデルではなく、表面的な音響特徴からの推測です。数値そのもの(計算結果)は確定的ですが、それが聴き手にどう作用するかという解釈は、あくまで仮説としてご覧ください。",
    aiHeading: "AIによる解説について",
    aiBody:
      "「AIによる解説」タブの文章はClaude(Anthropic)によって生成されます。実際に計算された数値・事実のみを根拠に書かれており、事実にない数値を作り出すことはありません。フォローアップ質問には、音楽理論の一般的な知識を使って自由に答えることがあります。",
    differentiationHeading: "ChatGPTに聞くのと何が違うのか",
    differentiationBody:
      "汎用AIに「この曲を解析して」と頼むと、そのAI自身がその場でコードを書いて計算し、同じAIがその結果を文章として説明します。計算と説明を分離する仕組みがないため、計算に紛れ込んだバグにAI自身が気づけないまま、自信を持って(誤った)数値を語ってしまうことがあります。このアプリは逆に、すべての数値を事前に構築し250件を超える自動テストで検証済みの決定的な計算パイプラインから得ています。AI(Claude)には、その検証済みの事実だけが渡され、それを自然な文章にする役割のみを担わせています — 自分で数値を計算する余地はありません。加えて、このアプリはテキストのやり取りだけでは実現できないことも行います: マイクを使ったリアルタイムの音程検出(歌ったり演奏したりしているその場で)、Tonnetz(和声幾何学)をドラッグ・ズームしながら探索できるインタラクティブな表示、パート選択を切り替えるたびに全ての指標が即座に再計算される体験などです。",
  },
  en: {
    heading: "About this site",
    intro:
      "Notewave is an interactive tool that runs mathematical analysis — acoustic physics, geometry (the Tonnetz), Fourier analysis, information theory (Shannon entropy) — over a song or your own playing/singing.",
    hypothesisHeading: "What the numbers mean",
    hypothesisBody:
      "The \"metrics that may correlate with beauty\" (consonance, harmonic tension, predictability, self-similarity) and the mood estimate (valence/arousal) are all a hypothesis-generating view based on mathematical correlation between music-theoretic/information-theoretic metrics and a song's impression or catchiness. They do not prove why a song sounds beautiful or why it sticks in the ear. The mood estimate in particular is a guess from surface acoustic features, not a validated emotion-recognition model. The numbers themselves (the computed results) are exact, but the interpretation of how they might affect a listener should be read as a hypothesis.",
    aiHeading: "About the AI explanation",
    aiBody:
      "The text in the \"AI Explanation\" tab is generated by Claude (Anthropic). It's written using only the numbers and facts actually computed — it never invents a number that wasn't in that data. Follow-up questions may draw on Claude's general music-theory knowledge as well.",
    differentiationHeading: "How is this different from just asking ChatGPT?",
    differentiationBody:
      "When you ask a general-purpose AI to \"analyze this song,\" the same model writes the analysis code on the spot and narrates the result. There's no separation between computing and narrating, so a bug in its improvised code can go unnoticed while the model still states the (wrong) numbers with full confidence. This app works the other way around: every number comes from a deterministic pipeline that was built and tested ahead of time (250+ automated tests), and Claude is only ever handed already-verified facts to turn into prose — it's never in a position to compute a number itself. This app also does things a text-based chat simply can't: real-time pitch tracking from your microphone while you sing or play, an interactive Tonnetz view you can drag and zoom through, and every metric recomputing instantly as you toggle which instrument parts to include.",
  },
};
