import type { Locale } from "../locale";

interface AboutDict {
  heading: string;
  intro: string;
  hypothesisHeading: string;
  hypothesisBody: string;
  aiHeading: string;
  aiBody: string;
}

export const aboutDict: Record<Locale, AboutDict> = {
  ja: {
    heading: "このサイトについて",
    intro:
      "「音楽の数学」は、曲やあなたの演奏・歌声を対象に、音響物理・幾何学(Tonnetz)・フーリエ解析・情報理論(シャノンエントロピー)に基づく数理的な解析を行うインタラクティブツールです。",
    hypothesisHeading: "数値が意味すること",
    hypothesisBody:
      "「美しさと相関しうる数理的特徴」(協和度・和声的テンション・予測可能性・自己相似性)や、感情推定(valence/arousal)は、いずれも音楽理論・情報理論上の数学的な指標と、曲の印象やキャッチーさとの相関に基づく仮説的な視点です。曲がなぜ美しく聴こえるか、なぜ耳に残るかを証明するものではありません。感情推定についても、検証済みの感情認識モデルではなく、表面的な音響特徴からの推測です。数値そのもの(計算結果)は確定的ですが、それが聴き手にどう作用するかという解釈は、あくまで仮説としてご覧ください。",
    aiHeading: "AIによる解説について",
    aiBody:
      "「AIによる解説」タブの文章はClaude(Anthropic)によって生成されます。実際に計算された数値・事実のみを根拠に書かれており、事実にない数値を作り出すことはありません。フォローアップ質問には、音楽理論の一般的な知識を使って自由に答えることがあります。",
  },
  en: {
    heading: "About this site",
    intro:
      "Music Math is an interactive tool that runs mathematical analysis — acoustic physics, geometry (the Tonnetz), Fourier analysis, information theory (Shannon entropy) — over a song or your own playing/singing.",
    hypothesisHeading: "What the numbers mean",
    hypothesisBody:
      "The \"metrics that may correlate with beauty\" (consonance, harmonic tension, predictability, self-similarity) and the mood estimate (valence/arousal) are all a hypothesis-generating view based on mathematical correlation between music-theoretic/information-theoretic metrics and a song's impression or catchiness. They do not prove why a song sounds beautiful or why it sticks in the ear. The mood estimate in particular is a guess from surface acoustic features, not a validated emotion-recognition model. The numbers themselves (the computed results) are exact, but the interpretation of how they might affect a listener should be read as a hypothesis.",
    aiHeading: "About the AI explanation",
    aiBody:
      "The text in the \"AI Explanation\" tab is generated by Claude (Anthropic). It's written using only the numbers and facts actually computed — it never invents a number that wasn't in that data. Follow-up questions may draw on Claude's general music-theory knowledge as well.",
  },
};
