import type { Locale } from "../locale";

interface AiExplanationTabDict {
  label: string;
  heading: string;
  description: string;
  generating: string;
  generate: string;
  footer: string;
  userLabel: string;
  assistantLabel: string;
  askPlaceholder: string;
  send: string;
  sending: string;
  followUpErrorFallback: string;
  level: { beginner: string; professional: string };
  undoEdit: string;
  editChangeLog: (counts: { added: number; edited: number; removed: number; skipped: number }) => string;
}

export const aiExplanationTabDict: Record<Locale, AiExplanationTabDict> = {
  ja: {
    label: "READING",
    heading: "AIによる解説",
    description: "これまでの数値解析結果のみを根拠に、曲の特徴を自然な文章としてまとめた、結論的な解釈です。",
    generating: "生成中…",
    generate: "AIによる解説を生成",
    footer: "Claude(Anthropic)による生成。上記の数値解析結果のみを根拠にしています。",
    userLabel: "あなた",
    assistantLabel: "AI",
    askPlaceholder: "この解説について質問する…",
    send: "送信",
    sending: "送信中…",
    followUpErrorFallback: "質問への回答生成に失敗しました",
    level: { beginner: "初心者向け", professional: "専門家向け" },
    undoEdit: "直前のAI編集を元に戻す",
    editChangeLog: ({ added, edited, removed, skipped }) =>
      `変更内容: 追加${added}件、編集${edited}件、削除${removed}件${skipped > 0 ? `(スキップ${skipped}件)` : ""}`,
  },
  en: {
    label: "READING",
    heading: "AI Explanation",
    description: "A concluding interpretation of the song's character, written in natural prose based only on the numerical analysis above.",
    generating: "Generating…",
    generate: "Generate AI Explanation",
    footer: "Generated by Claude (Anthropic), based only on the numerical analysis above.",
    userLabel: "You",
    assistantLabel: "AI",
    askPlaceholder: "Ask a follow-up question…",
    send: "Send",
    sending: "Sending…",
    followUpErrorFallback: "Failed to generate a reply",
    level: { beginner: "Beginner", professional: "Professional" },
    undoEdit: "Undo last AI edit",
    editChangeLog: ({ added, edited, removed, skipped }) =>
      `Changes: ${added} added, ${edited} edited, ${removed} removed${skipped > 0 ? ` (${skipped} skipped)` : ""}`,
  },
};
