import type { Locale } from "../locale";

interface AiExplanationTabDict {
  label: string;
  heading: string;
  description: string;
  generating: string;
  generate: string;
  footer: string;
  userLabel: string;
  assistantLabel: string;
  askPlaceholder: string;
  send: string;
  sending: string;
  followUpErrorFallback: string;
}

export const aiExplanationTabDict: Record<Locale, AiExplanationTabDict> = {
  ja: {
    label: "READING",
    heading: "AIによる解説",
    description: "これまでの数値解析結果のみを根拠に、曲の特徴を自然な文章としてまとめた、結論的な解釈です。",
    generating: "生成中…",
    generate: "AIによる解説を生成",
    footer: "Claude(Anthropic)による生成。上記の数値解析結果のみを根拠にしています。",
    userLabel: "あなた",
    assistantLabel: "AI",
    askPlaceholder: "この解説について質問する…",
    send: "送信",
    sending: "送信中…",
    followUpErrorFallback: "質問への回答生成に失敗しました",
  },
  en: {
    label: "READING",
    heading: "AI Explanation",
    description: "A concluding interpretation of the song's character, written in natural prose based only on the numerical analysis above.",
    generating: "Generating…",
    generate: "Generate AI Explanation",
    footer: "Generated by Claude (Anthropic), based only on the numerical analysis above.",
    userLabel: "You",
    assistantLabel: "AI",
    askPlaceholder: "Ask a follow-up question…",
    send: "Send",
    sending: "Sending…",
    followUpErrorFallback: "Failed to generate a reply",
  },
};
